name: secret_workflow_repo

on: [push]

jobs:
        job1:
                runs-on: ubuntu-latest
                steps:
                        -name: Step with a secret
                        run: |
                                echo "Hello Secret!"
                                echo "This is a secret value: ${{secrets.SECRET_TOKEN}}"
